### ISSUE TITLE
Backup/restore InfluxDB datasets in Kubernetes 

### ISSUE THREAD

**Issue by justb4** [smartemission/smartemission#139]
Currently (and later)  there is a need to restore all SE data from backups into the Kubernetes deployment. This concerns two types of database dumps:

* Postgres dumps
* InfluxDB dumps

Postgres is relatively straightforward, can be handled via external clients like `psql` and `pg_dump|restore`, plus PG in Azure Kubernetes is a hosted service, where backups are assumed.

InfluxDB is more of a challenge. The standard SE Docker deployment uses a [backup.sh ](https://github.com/smartemission/smartemission/blob/master/services/influxdb/backup.sh)and [restore.sh](https://github.com/smartemission/smartemission/blob/master/services/influxdb/restore.sh) script that basically calls `influxd backup|restore` commands using the SE InfluxDB Docker Image.

How to implement the equivalent backup|restore for InfluxDB in Kubernetes is the focus of this issue. A good starting point is here:
https://medium.com/innocode-stories/restore-influxdb-from-backup-in-kubernetes-c5b71ddbd825

**Comment by justb4** [comment]
Finally got restore working: "trick" is to specify the full name like `influxdb-storage-influxdb-0` in the `persistentVolumeClaim`

```
apiVersion: batch/v1
kind: Job
metadata:
  name: influxdb-restore
  namespace: smartemission
spec:
  parallelism: 1
  backoffLimit: 0
  template:
    metadata:
      name: influxdb-restore
    spec:
      containers:
        - name: influx
          image: "influxdb:1.5.3"
          command: ["/bin/sh"]
          args: ["-c", "influxd restore -metadir /var/lib/influxdb/meta -database smartemission -datadir /var/lib/influxdb/data /backup/influxdb/"]
          volumeMounts:
          - mountPath: /var/lib/influxdb
            name: influx
          - mountPath: /backup
            readOnly: true
            name: backup
      volumes:
        - name: backup
          persistentVolumeClaim:
            claimName: influxdb-backup-influxdb-0
        - name: influx
          persistentVolumeClaim:
            claimName: influxdb-storage-influxdb-0
      restartPolicy: Never

```
